name: "Sanctuary Updater"
description: "Updater for the Sanctuary Systems fork for of Home Assistant"
version: "15.2"
slug: "sanctuary-updater"
init: false
arch:
  - aarch64
#  - amd64
#  - armhf
#  - armv7
#  - i386
host_dbus: true
hassio_api: true
hassio_role: admin
map:
  - share:rw
options:
  ota_url: "http://pkg.sanctuary-systems.com/hassos/haos_rpi5-64-15.2.raucb"
schema:
  ota_url: url
image: "ghcr.io/sanctuary-systems-com/{arch}-sanctuary-updater"
