name: "Sanctuary Updater"
description: "Updater for the Sanctuary Systems fork for of Home Assistant"
version: "16.1.dev1756203741"
slug: "sanctuary-updater"
init: false
arch:
  - aarch64
#  - amd64
#  - armhf
#  - armv7
#  - i386
host_dbus: true
hassio_api: true
hassio_role: admin
map:
  - share:rw
options:
  force: false
schema:
  force: bool
image: "ghcr.io/sanctuary-systems-com/{arch}-sanctuary-updater"
