name: "llama.cpp"
description: "GPU accelerated llama.cpp using Vulkan"
version: "1.0.0"
slug: "llama.cpp"
init: false
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
video: true
ports:
  8765/tcp: 8765
image: "ghcr.io/sanctuary-systems-com/{arch}-llama-cpp-vulkan"
