name: "llama.cpp"
description: "GPU accelerated llama.cpp using Vulkan"
version: "1.0.0"
slug: "llama.cpp"
init: false
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
devices:
  - /dev/dri
  - /dev/kfd
image: "ghcr.io/sanctuary-systems-com/{arch}-llama-cpp-vulkan"