name: "llama.cpp"
description: "BROKEN! GPU accelerated llama.cpp using Vulkan"
version: "1.0.0"
slug: "llama.cpp"
init: false
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
video: true
ports:
  10202/tcp: 10202
options:
  repository: "NousResearch/Hermes-3-Llama-3.1-8B-GGUF"
  file: "Hermes-3-Llama-3.1-8B.Q4_K_M.gguf"
  chat_template: "NousResearch/Hermes-3-Llama-3.1-8B tool_use"
schema:
  repository: str
  file: str
  chat_template: str
image: "ghcr.io/sanctuary-systems-com/{arch}-llama-cpp-vulkan"
